### ISSUE TITLE
Add setting to hide/show plugin in main menu

### ISSUE THREAD

**Issue by piotrpog** [lindseydiloreto/craft-inventory#10]
I dont think all site users need to see this plugin link in main menu. Its not usefull for them and might lead to confusion.
Therefore, i propose making plugin avaible from "settings" page by default, and as I said in title, option to hide/show it in main menu.

**Comment by lindseydiloreto** [comment]
Interesting suggestion. Noted!

**Comment by niektenhoopen** [comment]
For anyone who reads this: you can also disable access to the Inventory plugin by setting user rights (or using user groups)

**Comment by lindseydiloreto** [comment]
At some point since this issue was originally filed, Craft introduced the concept of Utilities. We've gone ahead and converted the Field Inventory tool to a **Utility**, where it fits very naturally.

It can now be removed from the sidebar nav, while leaving it readily available for anyone who needs it. This change is available in [v3.0.0](https://github.com/doublesecretagency/craft-inventory/releases/tag/3.0.0).

It's a different approach, but I think it neatly solves the original problem! 👍
