### ISSUE TITLE
Clone fields

### ISSUE THREAD

**Issue by TomDeSmet** [lindseydiloreto/craft-inventory#13]
This is a feature from Field Manager. It seems Field Manager and inventory really compliment each other with some overlap, but it would be awesome if we only needed 1 plugin and cloning is my most used feature from Field Manager.
Inventory looks better, so hence my preference :)

**Comment by lindseydiloreto** [comment]
Ha, interesting feature request! It was only recently that you could even _delete_ unused fields directly from the Inventory page.

Let me put a little thought into it. I have some long-term plans for Inventory (over the next 6-12 months), it's hard to say if this FR is inline with those plans. If it is though, I'd be happy to include it! 👍

Thanks for the suggestion!

**Comment by lindseydiloreto** [comment]
Sorry we never added your feature request, but there's good news...

Craft has evolved significantly since this thread was created, and **Inventory is no longer needed in Craft 5!** 👏 

The plugin will not be ported to Craft 5, since all of the plugin's functionality is now part of the native field manager UX.
