### ISSUE TITLE
Matrix field inventory?

### ISSUE THREAD

**Issue by jwb009** [lindseydiloreto/craft-inventory#5]
Hi, nice plugin! Am I correct that this doesn't support matrix fields/blocks?
I'd like to delete a few blocks in my matrix field, but I'm not sure if those blocks are in use. This seems like the perfect plugin to determine that.

Thanks!

**Comment by lindseydiloreto** [comment]
Sorry for the delayed response.

No, this plugin currently won't help you with matrix blocks. It's an interesting feature request though, I'll make note of it for the future.

**Comment by jwb009** [comment]
No problem, thanks for the response!

In the meantime I just made a simple template that loops through all entries and lists each block being used...not pretty, but works in a pinch :
```
{% set entries = craft.entries.section(['projects','about','insights','news','careers']).limit(500) %}

{% for entry in entries.order('title') %}
  {{ entry.title }}
  {% for block in entry.blockBody %}
    {{ block.type.name }}<br>
  {% endfor %}
{% endfor %}

**Comment by lindseydiloreto** [comment]
Sorry we never added your feature request, but there's good news...

Craft has evolved significantly since this thread was created, and **Inventory is no longer needed in Craft 5!** 👏 

The plugin will not be ported to Craft 5, since all of the plugin's functionality is now part of the native field manager UX.
