### ISSUE TITLE
TypeError on Craft3

### ISSUE THREAD

**Issue by jmcgaha** [lindseydiloreto/craft-inventory#9]
I'm pretty sure this plugin was working on Craft3 a few weeks ago but last week I noticed this error occurring when loading the plugin. The weird part is that if I randomly add an id to the url some of them work, some don't.

Argument 1 passed to craft\services\Sections::getSectionById() must be of the type integer, null given, called in /chroot/home/domainname.com/vendor/doublesecretagency/craft-inventory/src/services/InventoryService.php on line 117

Error has occurred on our staging server which is:
Craft 3.0.14-15
PHP 7.0.28

I cannot get the error to show up on my local MAMP setup where I've tested both PHP 7.0 and 7.1.

**Comment by lindseydiloreto** [comment]
Hmm, interesting. Thanks for the heads up, I'll take a look!

**Comment by lindseydiloreto** [comment]
This is fixed in **2.0.2**.

It turns out, you had an orphaned field layout which was throwing an error. I'm not really sure _how_ you got an orphaned layout, but somehow it was there. By "orphaned", I mean that the field layout existed, but was not attached to anything (which is not normal).

If you detect an orphaned layout using Inventory, you can safely delete that layout directly in the database. Go to the `fieldlayouts` table, and find the `id` of the layout which has been orphaned. Deleting the layout here should properly ripple through and clean up any related orphaned data.
